// <auto-generated />
using System;
using DeviceStatusBeacon.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeviceStatusBeacon.Migrations {
	[DbContext(typeof(DeviceStatusBeaconContext))]
	[Migration("20260702051358_InitialCreate")]
	partial class InitialCreate {
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
			modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

			modelBuilder.Entity("ApiCredentialDevice", b => {
				b.Property<Guid>("AuthorizedApiCredentialsApiCredentialId")
					.HasColumnType("TEXT");

				b.Property<Guid>("AuthorizedDevicesDeviceId")
					.HasColumnType("TEXT");

				b.HasKey("AuthorizedApiCredentialsApiCredentialId", "AuthorizedDevicesDeviceId");

				b.HasIndex("AuthorizedDevicesDeviceId");

				b.ToTable("ApiCredentialDevice", t => {
					t.HasTrigger("TR_ApiCredentialDevice_EntityAuthInfoVersion_AfterDelete");

					t.HasTrigger("TR_ApiCredentialDevice_EntityAuthInfoVersion_AfterInsert");

					t.HasTrigger("TR_ApiCredentialDevice_EntityAuthInfoVersion_AfterUpdate");
				});

				b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
			});

			modelBuilder.Entity("DeviceStatusBeacon.Database.ApiCredential", b => {
				b.Property<Guid>("ApiCredentialId")
					.ValueGeneratedOnAdd()
					.HasColumnType("TEXT");

				b.Property<string>("DisplayName")
					.HasColumnType("TEXT");

				b.Property<bool>("Enabled")
					.HasColumnType("INTEGER");

				b.Property<byte[]>("ProtectedSecretKey")
					.IsRequired()
					.HasColumnType("BLOB");

				b.Property<int>("Role")
					.HasColumnType("INTEGER");

				b.Property<Guid>("UserId")
					.HasColumnType("TEXT");

				b.HasKey("ApiCredentialId");

				b.HasIndex("UserId", "DisplayName")
					.IsUnique();

				b.ToTable("ApiCredentials", t => {
					t.HasTrigger("TR_ApiCredentials_EntityAuthInfoVersion_AfterDelete");

					t.HasTrigger("TR_ApiCredentials_EntityAuthInfoVersion_AfterInsert");

					t.HasTrigger("TR_ApiCredentials_EntityAuthInfoVersion_AfterUpdate");

					t.HasCheckConstraint("CK_ApiCredentials_Role_PrincipalRole", "\"Role\" BETWEEN 0 AND 3");
				});

				b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
			});

			modelBuilder.Entity("DeviceStatusBeacon.Database.Device", b => {
				b.Property<Guid>("DeviceId")
					.ValueGeneratedOnAdd()
					.HasColumnType("TEXT");

				b.Property<string>("DeviceName")
					.IsRequired()
					.HasColumnType("TEXT");

				b.Property<string>("DisplayName")
					.HasColumnType("TEXT");

				b.Property<bool>("Enabled")
					.HasColumnType("INTEGER");

				b.Property<DateTime?>("LatestLogTime")
					.HasColumnType("TEXT");

				b.PrimitiveCollection<string>("LatestReportedAddresses")
					.HasColumnType("TEXT");

				b.Property<string>("LatestReporterRemoteAddress")
					.HasColumnType("TEXT");

				b.Property<string>("NormalizedDeviceName")
					.IsRequired()
					.HasColumnType("TEXT");

				b.Property<byte[]>("ProtectedSecretKey")
					.IsRequired()
					.HasColumnType("BLOB");

				b.HasKey("DeviceId");

				b.HasIndex("NormalizedDeviceName")
					.IsUnique();

				b.HasIndex("LatestLogTime", "NormalizedDeviceName")
					.IsDescending(true, false);

				b.ToTable("Devices", t => {
					t.HasTrigger("TR_Devices_EntityAuthInfoVersion_AfterAuthUpdate");

					t.HasTrigger("TR_Devices_EntityAuthInfoVersion_AfterDelete");

					t.HasTrigger("TR_Devices_EntityAuthInfoVersion_AfterInsert");

					t.HasCheckConstraint("CK_Devices_DeviceName_IdentityFormat", "\"DeviceName\" GLOB '[A-Za-z0-9]*'\r\nAND \"DeviceName\" GLOB '*[A-Za-z0-9]'\r\nAND length(\"DeviceName\") BETWEEN 4 AND 64\r\nAND \"DeviceName\" NOT GLOB '*[^A-Za-z0-9_-]*'");

					t.HasCheckConstraint("CK_Devices_LatestReportedAddresses_JsonArrayShape", "\"LatestReportedAddresses\" IS NULL\r\nOR (\r\n	json_valid(\"LatestReportedAddresses\")\r\n	AND json_type(\"LatestReportedAddresses\") = 'array'\r\n	AND json_array_length(\"LatestReportedAddresses\") > 0\r\n)");

					t.HasCheckConstraint("CK_Devices_NormalizedDeviceName_IdentityFormat", "\"NormalizedDeviceName\" GLOB '[A-Z0-9]*'\r\nAND \"NormalizedDeviceName\" GLOB '*[A-Z0-9]'\r\nAND length(\"NormalizedDeviceName\") BETWEEN 4 AND 64\r\nAND \"NormalizedDeviceName\" NOT GLOB '*[^A-Z0-9_-]*'");
				});

				b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
			});

			modelBuilder.Entity("DeviceStatusBeacon.Database.OnlineLog", b => {
				b.Property<long>("OnlineLogId")
					.ValueGeneratedOnAdd()
					.HasColumnType("INTEGER");

				b.Property<Guid>("DeviceId")
					.HasColumnType("TEXT");

				b.Property<DateTime>("LogTime")
					.HasColumnType("TEXT");

				b.Property<string>("Message")
					.HasColumnType("TEXT");

				b.PrimitiveCollection<string>("ReportedAddresses")
					.IsRequired()
					.HasColumnType("TEXT");

				b.Property<string>("ReporterRemoteAddress")
					.HasColumnType("TEXT");

				b.Property<Guid?>("SubmittedByUserId")
					.HasColumnType("TEXT");

				b.HasKey("OnlineLogId");

				b.HasIndex("LogTime");

				b.HasIndex("SubmittedByUserId");

				b.HasIndex("DeviceId", "LogTime");

				b.HasIndex("DeviceId", "OnlineLogId");

				b.ToTable("OnlineLogs", t => {
					t.HasTrigger("TR_OnlineLogs_DeviceSummary_AfterDelete");

					t.HasTrigger("TR_OnlineLogs_DeviceSummary_AfterInsert");

					t.HasTrigger("TR_OnlineLogs_DeviceSummary_AfterUpdate");

					t.HasCheckConstraint("CK_OnlineLogs_ReportedAddresses_JsonArrayShape", "json_valid(\"ReportedAddresses\")\r\nAND json_type(\"ReportedAddresses\") = 'array'\r\nAND json_array_length(\"ReportedAddresses\") > 0");
				});

				b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
			});

			modelBuilder.Entity("DeviceStatusBeacon.Database.SettingInDb", b => {
				b.Property<string>("Key")
					.HasColumnType("TEXT");

				b.Property<string>("Value")
					.HasColumnType("TEXT");

				b.HasKey("Key");

				b.ToTable("Settings", t => {
					t.HasCheckConstraint("CK_Settings_Key_NotEmpty", "length(\"Key\") > 0");
				});

				b.HasData(
					new {
						Key = "EntityAuthInfoVersion",
						Value = "0"
					});
			});

			modelBuilder.Entity("DeviceStatusBeacon.Database.User", b => {
				b.Property<Guid>("Id")
					.ValueGeneratedOnAdd()
					.HasColumnType("TEXT");

				b.Property<int>("AccessFailedCount")
					.HasColumnType("INTEGER");

				b.Property<string>("ConcurrencyStamp")
					.IsConcurrencyToken()
					.HasColumnType("TEXT");

				b.Property<string>("DisplayName")
					.HasColumnType("TEXT");

				b.Property<string>("Email")
					.HasMaxLength(256)
					.HasColumnType("TEXT");

				b.Property<bool>("EmailConfirmed")
					.HasColumnType("INTEGER");

				b.Property<bool>("LockoutEnabled")
					.HasColumnType("INTEGER");

				b.Property<DateTimeOffset?>("LockoutEnd")
					.HasColumnType("TEXT");

				b.Property<string>("NormalizedEmail")
					.HasMaxLength(256)
					.HasColumnType("TEXT");

				b.Property<string>("NormalizedUserName")
					.HasMaxLength(256)
					.HasColumnType("TEXT");

				b.Property<string>("PasswordHash")
					.HasColumnType("TEXT");

				b.Property<string>("PhoneNumber")
					.HasColumnType("TEXT");

				b.Property<bool>("PhoneNumberConfirmed")
					.HasColumnType("INTEGER");

				b.Property<string>("SecurityStamp")
					.HasColumnType("TEXT");

				b.Property<bool>("TwoFactorEnabled")
					.HasColumnType("INTEGER");

				b.Property<string>("UserName")
					.HasMaxLength(256)
					.HasColumnType("TEXT");

				b.HasKey("Id");

				b.HasIndex("NormalizedEmail")
					.HasDatabaseName("EmailIndex");

				b.HasIndex("NormalizedUserName")
					.IsUnique()
					.HasDatabaseName("UserNameIndex");

				b.ToTable("AspNetUsers", (string)null);
			});

			modelBuilder.Entity("DeviceStatusBeacon.Database.UserRole", b => {
				b.Property<Guid>("UserId")
					.HasColumnType("TEXT");

				b.Property<Guid>("RoleId")
					.HasColumnType("TEXT");

				b.HasKey("UserId", "RoleId");

				b.HasIndex("RoleId");

				b.HasIndex("UserId")
					.IsUnique();

				b.ToTable("AspNetUserRoles", (string)null);
			});

			modelBuilder.Entity("DeviceUser", b => {
				b.Property<Guid>("AuthorizedDevicesDeviceId")
					.HasColumnType("TEXT");

				b.Property<Guid>("AuthorizedUsersId")
					.HasColumnType("TEXT");

				b.HasKey("AuthorizedDevicesDeviceId", "AuthorizedUsersId");

				b.HasIndex("AuthorizedUsersId");

				b.ToTable("DeviceUser");
			});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b => {
				b.Property<Guid>("Id")
					.ValueGeneratedOnAdd()
					.HasColumnType("TEXT");

				b.Property<string>("ConcurrencyStamp")
					.IsConcurrencyToken()
					.HasColumnType("TEXT");

				b.Property<string>("Name")
					.HasMaxLength(256)
					.HasColumnType("TEXT");

				b.Property<string>("NormalizedName")
					.HasMaxLength(256)
					.HasColumnType("TEXT");

				b.HasKey("Id");

				b.HasIndex("NormalizedName")
					.IsUnique()
					.HasDatabaseName("RoleNameIndex");

				b.ToTable("AspNetRoles", (string)null);

				b.HasData(
					new {
						Id = new Guid("5121009f-b5bd-4ec7-95ee-edb11bca4f92"),
						ConcurrencyStamp = "5121009f-b5bd-4ec7-95ee-edb11bca4f92",
						Name = "LimitedQuery",
						NormalizedName = "LIMITEDQUERY"
					},
					new {
						Id = new Guid("0e132786-0e18-4cd1-bf41-cfdd18b12d90"),
						ConcurrencyStamp = "0e132786-0e18-4cd1-bf41-cfdd18b12d90",
						Name = "FullQuery",
						NormalizedName = "FULLQUERY"
					},
					new {
						Id = new Guid("a8a0d700-c15d-487a-97c6-3359113d367f"),
						ConcurrencyStamp = "a8a0d700-c15d-487a-97c6-3359113d367f",
						Name = "DeviceManager",
						NormalizedName = "DEVICEMANAGER"
					},
					new {
						Id = new Guid("3df54d97-ee56-47f1-a1c0-3044dbdb8e41"),
						ConcurrencyStamp = "3df54d97-ee56-47f1-a1c0-3044dbdb8e41",
						Name = "Administrator",
						NormalizedName = "ADMINISTRATOR"
					});
			});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b => {
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasColumnType("INTEGER");

				b.Property<string>("ClaimType")
					.HasColumnType("TEXT");

				b.Property<string>("ClaimValue")
					.HasColumnType("TEXT");

				b.Property<Guid>("RoleId")
					.HasColumnType("TEXT");

				b.HasKey("Id");

				b.HasIndex("RoleId");

				b.ToTable("AspNetRoleClaims", (string)null);
			});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b => {
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasColumnType("INTEGER");

				b.Property<string>("ClaimType")
					.HasColumnType("TEXT");

				b.Property<string>("ClaimValue")
					.HasColumnType("TEXT");

				b.Property<Guid>("UserId")
					.HasColumnType("TEXT");

				b.HasKey("Id");

				b.HasIndex("UserId");

				b.ToTable("AspNetUserClaims", (string)null);
			});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b => {
				b.Property<string>("LoginProvider")
					.HasColumnType("TEXT");

				b.Property<string>("ProviderKey")
					.HasColumnType("TEXT");

				b.Property<string>("ProviderDisplayName")
					.HasColumnType("TEXT");

				b.Property<Guid>("UserId")
					.HasColumnType("TEXT");

				b.HasKey("LoginProvider", "ProviderKey");

				b.HasIndex("UserId");

				b.ToTable("AspNetUserLogins", (string)null);
			});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b => {
				b.Property<Guid>("UserId")
					.HasColumnType("TEXT");

				b.Property<string>("LoginProvider")
					.HasColumnType("TEXT");

				b.Property<string>("Name")
					.HasColumnType("TEXT");

				b.Property<string>("Value")
					.HasColumnType("TEXT");

				b.HasKey("UserId", "LoginProvider", "Name");

				b.ToTable("AspNetUserTokens", (string)null);
			});

			modelBuilder.Entity("ApiCredentialDevice", b => {
				b.HasOne("DeviceStatusBeacon.Database.ApiCredential", null)
					.WithMany()
					.HasForeignKey("AuthorizedApiCredentialsApiCredentialId")
					.OnDelete(DeleteBehavior.Cascade)
					.IsRequired();

				b.HasOne("DeviceStatusBeacon.Database.Device", null)
					.WithMany()
					.HasForeignKey("AuthorizedDevicesDeviceId")
					.OnDelete(DeleteBehavior.Cascade)
					.IsRequired();
			});

			modelBuilder.Entity("DeviceStatusBeacon.Database.ApiCredential", b => {
				b.HasOne("DeviceStatusBeacon.Database.User", "User")
					.WithMany("ApiCredentials")
					.HasForeignKey("UserId")
					.OnDelete(DeleteBehavior.Cascade)
					.IsRequired();

				b.Navigation("User");
			});

			modelBuilder.Entity("DeviceStatusBeacon.Database.OnlineLog", b => {
				b.HasOne("DeviceStatusBeacon.Database.Device", "Device")
					.WithMany("OnlineLogs")
					.HasForeignKey("DeviceId")
					.OnDelete(DeleteBehavior.Cascade)
					.IsRequired();

				b.HasOne("DeviceStatusBeacon.Database.User", "SubmittedByUser")
					.WithMany("SubmittedOnlineLogs")
					.HasForeignKey("SubmittedByUserId")
					.OnDelete(DeleteBehavior.SetNull);

				b.Navigation("Device");

				b.Navigation("SubmittedByUser");
			});

			modelBuilder.Entity("DeviceStatusBeacon.Database.UserRole", b => {
				b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", "Role")
					.WithMany()
					.HasForeignKey("RoleId")
					.OnDelete(DeleteBehavior.Restrict)
					.IsRequired();

				b.HasOne("DeviceStatusBeacon.Database.User", "User")
					.WithMany("UserRoles")
					.HasForeignKey("UserId")
					.OnDelete(DeleteBehavior.Cascade)
					.IsRequired();

				b.Navigation("Role");

				b.Navigation("User");
			});

			modelBuilder.Entity("DeviceUser", b => {
				b.HasOne("DeviceStatusBeacon.Database.Device", null)
					.WithMany()
					.HasForeignKey("AuthorizedDevicesDeviceId")
					.OnDelete(DeleteBehavior.Cascade)
					.IsRequired();

				b.HasOne("DeviceStatusBeacon.Database.User", null)
					.WithMany()
					.HasForeignKey("AuthorizedUsersId")
					.OnDelete(DeleteBehavior.Cascade)
					.IsRequired();
			});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b => {
				b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
					.WithMany()
					.HasForeignKey("RoleId")
					.OnDelete(DeleteBehavior.Cascade)
					.IsRequired();
			});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b => {
				b.HasOne("DeviceStatusBeacon.Database.User", null)
					.WithMany()
					.HasForeignKey("UserId")
					.OnDelete(DeleteBehavior.Cascade)
					.IsRequired();
			});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b => {
				b.HasOne("DeviceStatusBeacon.Database.User", null)
					.WithMany()
					.HasForeignKey("UserId")
					.OnDelete(DeleteBehavior.Cascade)
					.IsRequired();
			});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b => {
				b.HasOne("DeviceStatusBeacon.Database.User", null)
					.WithMany()
					.HasForeignKey("UserId")
					.OnDelete(DeleteBehavior.Cascade)
					.IsRequired();
			});

			modelBuilder.Entity("DeviceStatusBeacon.Database.Device", b => {
				b.Navigation("OnlineLogs");
			});

			modelBuilder.Entity("DeviceStatusBeacon.Database.User", b => {
				b.Navigation("ApiCredentials");

				b.Navigation("SubmittedOnlineLogs");

				b.Navigation("UserRoles");
			});
#pragma warning restore 612, 618
		}
	}
}