// <auto-generated />
using System;
using DeviceStatusBeacon.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeviceStatusBeacon.Migrations
{
    [DbContext(typeof(DeviceStatusBeaconContext))]
    [Migration("20260205154715_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("AccountDevice", b =>
                {
                    b.Property<Guid>("AuthorizedAccountsAccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QueryableDevicesDeviceId")
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorizedAccountsAccountId", "QueryableDevicesDeviceId");

                    b.HasIndex("QueryableDevicesDeviceId");

                    b.ToTable("AccountDevice");
                });

            modelBuilder.Entity("DeviceStatusBeacon.Models.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ProtectedSecretKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("DeviceStatusBeacon.Models.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LatestLogTime")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("LatestReportedAddresses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestReporterRemoteAddress")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ProtectedSecretKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("DeviceId");

                    b.HasIndex("DeviceName")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("DeviceStatusBeacon.Models.OnlineLog", b =>
                {
                    b.Property<long>("OnlineLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ReportedAddresses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReporterRemoteAddress")
                        .HasColumnType("TEXT");

                    b.HasKey("OnlineLogId");

                    b.HasIndex("LogTime");

                    b.HasIndex("DeviceId", "LogTime");

                    b.ToTable("OnlineLogs");
                });

            modelBuilder.Entity("AccountDevice", b =>
                {
                    b.HasOne("DeviceStatusBeacon.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("AuthorizedAccountsAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeviceStatusBeacon.Models.Device", null)
                        .WithMany()
                        .HasForeignKey("QueryableDevicesDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeviceStatusBeacon.Models.OnlineLog", b =>
                {
                    b.HasOne("DeviceStatusBeacon.Models.Device", "Device")
                        .WithMany("OnlineLogs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("DeviceStatusBeacon.Models.Device", b =>
                {
                    b.Navigation("OnlineLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
