// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace DeviceStatusBeacon
{
    public partial class DeviceStatusBeaconContextModel
    {
        private DeviceStatusBeaconContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("a4e0722c-085c-4044-a043-e9387a54e4ac"), entityTypeCount: 4)
        {
        }

        partial void Initialize()
        {
            var accountDevice = AccountDeviceEntityType.Create(this);
            var account = AccountEntityType.Create(this);
            var device = DeviceEntityType.Create(this);
            var onlineLog = OnlineLogEntityType.Create(this);

            AccountDeviceEntityType.CreateForeignKey1(accountDevice, account);
            AccountDeviceEntityType.CreateForeignKey2(accountDevice, device);
            OnlineLogEntityType.CreateForeignKey1(onlineLog, device);

            AccountEntityType.CreateSkipNavigation1(account, device, accountDevice);
            DeviceEntityType.CreateSkipNavigation1(device, account, accountDevice);

            AccountDeviceEntityType.CreateAnnotations(accountDevice);
            AccountEntityType.CreateAnnotations(account);
            DeviceEntityType.CreateAnnotations(device);
            OnlineLogEntityType.CreateAnnotations(onlineLog);

            AddAnnotation("ProductVersion", "10.0.2");
        }
    }
}
