// <auto-generated />
using DeviceStatusBeacon;
using DeviceStatusBeacon.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(DeviceStatusBeaconContext), typeof(DeviceStatusBeaconContextModel))]
